cmd /c gcc -DACD_IS_API_ONLY -DFIXED_WING_TAWS -E -P C:\Scala\Git\C_to_Scala\beforePre\ac_data.c > noincludes\ac_data.c
cmd /c gcc -DACD_IS_API_ONLY -DFIXED_WING_TAWS -E -P C:\Scala\Git\C_to_Scala\beforePre\ac_data.h > noincludes\ac_data.h
cmd /c gcc -DACD_IS_API_ONLY -DFIXED_WING_TAWS -E -P C:\Scala\Git\C_to_Scala\beforePre\ang_util.c > noincludes\ang_util.c
cmd /c gcc -DACD_IS_API_ONLY -DFIXED_WING_TAWS -E -P C:\Scala\Git\C_to_Scala\beforePre\ang_util.h > noincludes\ang_util.h
cmd /c gcc -DACD_IS_API_ONLY -DFIXED_WING_TAWS -E -P C:\Scala\Git\C_to_Scala\beforePre\api_a424_defs.h > noincludes\api_a424_defs.h
cmd /c gcc -DACD_IS_API_ONLY -DFIXED_WING_TAWS -E -P C:\Scala\Git\C_to_Scala\beforePre\api_common.h > noincludes\api_common.h
cmd /c gcc -DACD_IS_API_ONLY -DFIXED_WING_TAWS -E -P C:\Scala\Git\C_to_Scala\beforePre\api_obst_defs.h > noincludes\api_obst_defs.h
cmd /c gcc -DACD_IS_API_ONLY -DFIXED_WING_TAWS -E -P C:\Scala\Git\C_to_Scala\beforePre\api_terr_defs.h > noincludes\api_terr_defs.h
cmd /c gcc -DACD_IS_API_ONLY -DFIXED_WING_TAWS -E -P C:\Scala\Git\C_to_Scala\beforePre\avg_util.c > noincludes\avg_util.c
cmd /c gcc -DACD_IS_API_ONLY -DFIXED_WING_TAWS -E -P C:\Scala\Git\C_to_Scala\beforePre\avg_util.h > noincludes\avg_util.h
cmd /c gcc -DACD_IS_API_ONLY -DFIXED_WING_TAWS -E -P C:\Scala\Git\C_to_Scala\beforePre\latlon_util.c > noincludes\latlon_util.c
cmd /c gcc -DACD_IS_API_ONLY -DFIXED_WING_TAWS -E -P C:\Scala\Git\C_to_Scala\beforePre\latlon_util.h > noincludes\latlon_util.h
cmd /c gcc -DACD_IS_API_ONLY -DFIXED_WING_TAWS -E -P C:\Scala\Git\C_to_Scala\beforePre\pre_ac_data.h > noincludes\pre_ac_data.h
cmd /c gcc -DACD_IS_API_ONLY -DFIXED_WING_TAWS -E -P C:\Scala\Git\C_to_Scala\beforePre\taws_api.c > noincludes\taws_api.c
cmd /c gcc -DACD_IS_API_ONLY -DFIXED_WING_TAWS -E -P C:\Scala\Git\C_to_Scala\beforePre\taws_api.h > noincludes\taws_api.h
cmd /c gcc -DACD_IS_API_ONLY -DFIXED_WING_TAWS -E -P C:\Scala\Git\C_to_Scala\beforePre\taws_callouts.c > noincludes\taws_callouts.c
cmd /c gcc -DACD_IS_API_ONLY -DFIXED_WING_TAWS -E -P C:\Scala\Git\C_to_Scala\beforePre\ta_alert.c > noincludes\ta_alert.c
cmd /c gcc -DACD_IS_API_ONLY -DFIXED_WING_TAWS -E -P C:\Scala\Git\C_to_Scala\beforePre\ta_defs.h > noincludes\ta_defs.h
cmd /c gcc -DACD_IS_API_ONLY -DFIXED_WING_TAWS -E -P C:\Scala\Git\C_to_Scala\beforePre\ta_gpws.c > noincludes\ta_gpws.c
cmd /c gcc -DACD_IS_API_ONLY -DFIXED_WING_TAWS -E -P C:\Scala\Git\C_to_Scala\beforePre\ta_line.c > noincludes\ta_line.c
cmd /c gcc -DACD_IS_API_ONLY -DFIXED_WING_TAWS -E -P C:\Scala\Git\C_to_Scala\beforePre\ta_line.h > noincludes\ta_line.h
cmd /c gcc -DACD_IS_API_ONLY -DFIXED_WING_TAWS -E -P C:\Scala\Git\C_to_Scala\beforePre\ta_lowalt.c > noincludes\ta_lowalt.c
cmd /c gcc -DACD_IS_API_ONLY -DFIXED_WING_TAWS -E -P C:\Scala\Git\C_to_Scala\beforePre\ta_main.c > noincludes\ta_main.c
cmd /c gcc -DACD_IS_API_ONLY -DFIXED_WING_TAWS -E -P C:\Scala\Git\C_to_Scala\beforePre\ta_main.h > noincludes\ta_main.h
cmd /c gcc -DACD_IS_API_ONLY -DFIXED_WING_TAWS -E -P C:\Scala\Git\C_to_Scala\beforePre\ta_obstacle.c > noincludes\ta_obstacle.c
cmd /c gcc -DACD_IS_API_ONLY -DFIXED_WING_TAWS -E -P C:\Scala\Git\C_to_Scala\beforePre\ta_parameters.c > noincludes\ta_parameters.c
cmd /c gcc -DACD_IS_API_ONLY -DFIXED_WING_TAWS -E -P C:\Scala\Git\C_to_Scala\beforePre\ta_parameters.h > noincludes\ta_parameters.h
cmd /c gcc -DACD_IS_API_ONLY -DFIXED_WING_TAWS -E -P C:\Scala\Git\C_to_Scala\beforePre\ta_pda.c > noincludes\ta_pda.c
cmd /c gcc -DACD_IS_API_ONLY -DFIXED_WING_TAWS -E -P C:\Scala\Git\C_to_Scala\beforePre\ta_pof.c > noincludes\ta_pof.c
cmd /c gcc -DACD_IS_API_ONLY -DFIXED_WING_TAWS -E -P C:\Scala\Git\C_to_Scala\beforePre\ta_pred.c > noincludes\ta_pred.c
cmd /c gcc -DACD_IS_API_ONLY -DFIXED_WING_TAWS -E -P C:\Scala\Git\C_to_Scala\beforePre\ta_util.c > noincludes\ta_util.c
cmd /c gcc -DACD_IS_API_ONLY -DFIXED_WING_TAWS -E -P C:\Scala\Git\C_to_Scala\beforePre\ta_util.h > noincludes\ta_util.h
cmd /c gcc -DACD_IS_API_ONLY -DFIXED_WING_TAWS -E -P C:\Scala\Git\C_to_Scala\beforePre\ta_vap.c > noincludes\ta_vap.c
cmd /c gcc -DACD_IS_API_ONLY -DFIXED_WING_TAWS -E -P C:\Scala\Git\C_to_Scala\beforePre\terr_util.c > noincludes\terr_util.c
cmd /c gcc -DACD_IS_API_ONLY -DFIXED_WING_TAWS -E -P C:\Scala\Git\C_to_Scala\beforePre\terr_util.h > noincludes\terr_util.h
cmd /c gcc -DACD_IS_API_ONLY -DFIXED_WING_TAWS -E -P C:\Scala\Git\C_to_Scala\beforePre\trig.c > noincludes\trig.c
cmd /c gcc -DACD_IS_API_ONLY -DFIXED_WING_TAWS -E -P C:\Scala\Git\C_to_Scala\beforePre\trig.h > noincludes\trig.h
exit
